### ISSUE TITLE
allow additional column types

### ISSUE THREAD

**Issue by smgogarten** [UW-GAC/AnvilDataModels#2]
Currently allowed types are varchar, bool, int, float, and enum.

Add datetime, possibly others.

**Comment by smgogarten** [comment]
@bheavner @amstilp 
Do we need to store date-times in the data models, or just dates? The [draft GREGoR data model](https://github.com/UW-GAC/gregor_data_models/blob/main/GREGoR_data_model_draft.dbml) has things like `sample_collection_timestamp` and `date_data_generation` which are both listed as `datetime`, but do we actually expect times or just dates? And if we expect both, should we distinguish between them? 

[Hadley Wickham says](https://r4ds.had.co.nz/dates-and-times.html#creating-datetimes): 
> You should always use the simplest possible data type that works for your needs. That means if you can use a date instead of a date-time, you should. Date-times are substantially more complicated because of the need to handle time zones

**Comment by amstilp** [comment]
If you use just a date, you can't differentiate between eg two uploads that happened on the same day. By "If we expect both, should we distinguish between them", do you mean call things that are datetimes "timestamp" and call things that are dates "date"? or something else?

**Comment by smgogarten** [comment]
I think we should have both "date" and "datetime", and only use "datetime" when it's really needed. When the data model is read into R they will become different types.

**Comment by smgogarten** [comment]
"date" and "datetime" added in 6cd59fa
